In [1]:
import pandas as pd

In [2]:
Data = {"Roll no": [21,22,23,24,25],"English": [52,63,45,85,30],"Science":[66,93,56,54,45],"Maths": [55,74,56,32,52]}
df = pd.DataFrame(Data,index = ["john","mohan","rohan","sohan","zohan"])
df

       Roll no  English  Science  Maths
john        21       52       66     55
mohan       22       63       93     74
rohan       23       45       56     56
sohan       24       85       54     32
zohan       25       30       45     52

In [3]:
df.head()

       Roll no  English  Science  Maths
john        21       52       66     55
mohan       22       63       93     74
rohan       23       45       56     56
sohan       24       85       54     32
zohan       25       30       45     52

In [4]:
df.tail()

       Roll no  English  Science  Maths
john        21       52       66     55
mohan       22       63       93     74
rohan       23       45       56     56
sohan       24       85       54     32
zohan       25       30       45     52

In [6]:
df.loc[["john","mohan"]]

       Roll no  English  Science  Maths
john        21       52       66     55
mohan       22       63       93     74

In [8]:
df.loc[["john","mohan"], ["English","Science"]]

       English  Science
john        52       66
mohan       63       93

In [12]:
df.iloc[0:3]

       Roll no  English  Science  Maths
john        21       52       66     55
mohan       22       63       93     74
rohan       23       45       56     56

In [21]:
df.iloc[0:5,0:4]

       Roll no  English  Science  Maths
john        21       52       66     55
mohan       22       63       93     74
rohan       23       45       56     56
sohan       24       85       54     32
zohan       25       30       45     52

In [22]:
df.iloc[0,1]

np.int64(52)

In [23]:
df.iloc[2,2]

np.int64(56)

In [25]:
print("Answer is")
df.iloc[3,2]

Answer is

np.int64(54)

In [31]:
df.loc[["mohan","rohan"],["English","Maths"]]

       English  Maths
mohan       63     74
rohan       45     56