# Pandas Practice (solutions)

This notebook offers a set of solutions to different tasks with pandas.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to pandas notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [pandas documnetation](https://pandas.pydata.org/pandas-docs/stable/).

In [1]:
# Import pandas
import pandas as pd

In [2]:
# Create a series of three different colours
colours = pd.Series(["Blue", "Red", "White"])

In [3]:
# View the series of different colours
colours

0     Blue
1      Red
2    White
dtype: str

In [4]:
# Create a series of three different car types and view it
cars = pd.Series(["BMW", "Toyota", "Honda"])
cars

0       BMW
1    Toyota
2     Honda
dtype: str

In [5]:
# Combine the Series of cars and colours into a DataFrame
car_data = pd.DataFrame({"Car make": cars,
                         "Colour": colours})
car_data

  Car make Colour
0      BMW   Blue
1   Toyota    Red
2    Honda  White

In [6]:
# Import "../data/car-sales.csv" and turn it into a DataFrame
car_sales = pd.read_csv("makers.csv")
car_sales

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Make,Colour,Odometer KM,Doors,Price
0,0,0,0,0,0,Toyota,white,150043,4,4000.0
1,1,1,1,1,1,Honda,red,87899,4,5000.0
2,2,2,2,2,2,Toyota,blue,32549,3,7000.0
3,3,3,3,3,3,BMW,black,11179,5,22000.0
4,4,4,4,4,4,Nissan,white,213095,4,3500.0
5,5,5,5,5,5,Toyota,green,99213,4,4500.0
6,6,6,6,6,6,Honda,blue,45698,4,7500.0
7,7,7,7,7,7,Honda,blue,54738,4,7000.0
8,8,8,8,8,8,Toyota,white,60000,4,6250.0
9,9,9,9,9,9,Nissan,white,31600,4,9700.0

In [7]:
# Export the DataFrame you created to a .csv file
car_sales.to_csv("makers.csv")

In [8]:
# Find the different datatypes of the car data DataFrame
car_sales.dtypes

Unnamed: 0.4      int64
Unnamed: 0.3      int64
Unnamed: 0.2      int64
Unnamed: 0.1      int64
Unnamed: 0        int64
Make                str
Colour              str
Odometer KM       int64
Doors             int64
Price           float64
dtype: object

In [9]:
# Describe your current car sales DataFrame using describe()
car_sales.describe()

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Odometer KM,Doors,Price
count,10.00000,10.00000,10.00000,10.00000,10.00000,10.000000,10.000000,10.000000
mean,4.50000,4.50000,4.50000,4.50000,4.50000,78601.400000,4.000000,7645.000000
std,3.02765,3.02765,3.02765,3.02765,3.02765,61983.471735,0.471405,5379.407753
min,0.00000,0.00000,0.00000,0.00000,0.00000,11179.000000,3.000000,3500.000000
25%,2.25000,2.25000,2.25000,2.25000,2.25000,35836.250000,4.000000,4625.000000
50%,4.50000,4.50000,4.50000,4.50000,4.50000,57369.000000,4.000000,6625.000000
75%,6.75000,6.75000,6.75000,6.75000,6.75000,96384.500000,4.000000,7375.000000
max,9.00000,9.00000,9.00000,9.00000,9.00000,213095.000000,5.000000,22000.000000

In [10]:
# Get information about your DataFrame using info()
car_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 10 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0.4  10 non-null     int64
 1   Unnamed: 0.3  10 non-null     int64
 2   Unnamed: 0.2  10 non-null     int64
 3   Unnamed: 0.1  10 non-null     int64
 4   Unnamed: 0    10 non-null     int64
 5   Make          10 non-null     str
 6   Colour        10 non-null     str
 7   Odometer KM   10 non-null     int64
 8   Doors         10 non-null     int64
 9   Price         10 non-null     float64
dtypes: float64(1), int64(7), str(2)
memory usage: 932.0 bytes

What does it show you?

In [11]:
# Create a Series of different numbers and find the mean of them
series = pd.Series([999, 22203, 43920])
series.mean()

np.float64(22374.0)

In [12]:
# Create a Series of different numbers and find the sum of them
series = pd.Series([482392, 34994, 22])
series.sum()

np.int64(517408)

In [13]:
# List out all the column names of the car sales DataFrame
car_sales.columns

Index(['Unnamed: 0.4', 'Unnamed: 0.3', 'Unnamed: 0.2', 'Unnamed: 0.1',
       'Unnamed: 0', 'Make', 'Colour', 'Odometer KM', 'Doors', 'Price'],
      dtype='str')

In [14]:
# Find the length of the car sales DataFrame
len(car_sales)

10

In [15]:
# Show the first 5 rows of the car sales DataFrame
car_sales.head()

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Make,Colour,Odometer KM,Doors,Price
0,0,0,0,0,0,Toyota,white,150043,4,4000.0
1,1,1,1,1,1,Honda,red,87899,4,5000.0
2,2,2,2,2,2,Toyota,blue,32549,3,7000.0
3,3,3,3,3,3,BMW,black,11179,5,22000.0
4,4,4,4,4,4,Nissan,white,213095,4,3500.0

In [16]:
# Show the first 7 rows of the car sales DataFrame
car_sales.head(7)

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Make,Colour,Odometer KM,Doors,Price
0,0,0,0,0,0,Toyota,white,150043,4,4000.0
1,1,1,1,1,1,Honda,red,87899,4,5000.0
2,2,2,2,2,2,Toyota,blue,32549,3,7000.0
3,3,3,3,3,3,BMW,black,11179,5,22000.0
4,4,4,4,4,4,Nissan,white,213095,4,3500.0
5,5,5,5,5,5,Toyota,green,99213,4,4500.0
6,6,6,6,6,6,Honda,blue,45698,4,7500.0

In [17]:
# Show the bottom 5 rows of the car sales DataFrame
car_sales.tail()

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Make,Colour,Odometer KM,Doors,Price
5,5,5,5,5,5,Toyota,green,99213,4,4500.0
6,6,6,6,6,6,Honda,blue,45698,4,7500.0
7,7,7,7,7,7,Honda,blue,54738,4,7000.0
8,8,8,8,8,8,Toyota,white,60000,4,6250.0
9,9,9,9,9,9,Nissan,white,31600,4,9700.0

In [18]:
# Use .loc to select the row at index 3 of the car sales DataFrame
car_sales.loc[3]

Unnamed: 0.4          3
Unnamed: 0.3          3
Unnamed: 0.2          3
Unnamed: 0.1          3
Unnamed: 0            3
Make                BMW
Colour            black
Odometer KM       11179
Doors                 5
Price           22000.0
Name: 3, dtype: object

In [19]:
# Use .iloc to select the row at position 3 of the car sales DataFrame
car_sales.iloc[3]

Unnamed: 0.4          3
Unnamed: 0.3          3
Unnamed: 0.2          3
Unnamed: 0.1          3
Unnamed: 0            3
Make                BMW
Colour            black
Odometer KM       11179
Doors                 5
Price           22000.0
Name: 3, dtype: object

Notice how they're the same? Why do you think this is? 

Check the pandas documentation for [.loc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html) and [.iloc](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html). Think about a different situation each could be used for and try them out.

In [20]:
# Select the "Odometer (KM)" column from the car sales DataFrame
car_sales["Odometer KM"]

0    150043
1     87899
2     32549
3     11179
4    213095
5     99213
6     45698
7     54738
8     60000
9     31600
Name: Odometer KM, dtype: int64

In [21]:
# Find the mean of the "Odometer (KM)" column in the car sales DataFrame
car_sales["Odometer KM"].mean()

np.float64(78601.4)

In [22]:
# Select the rows with over 100,000 kilometers on the Odometer
car_sales[car_sales["Odometer KM"] > 100000]

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Make,Colour,Odometer KM,Doors,Price
0,0,0,0,0,0,Toyota,white,150043,4,4000.0
4,4,4,4,4,4,Nissan,white,213095,4,3500.0

In [23]:
# Create a crosstab of the Make and Doors columns
pd.crosstab(car_sales["Make"], car_sales["Doors"])

Doors   3  4  5
Make
BMW     0  0  1
Honda   0  3  0
Nissan  0  2  0
Toyota  1  3  0

In [24]:
# Group columns of the car sales DataFrame by the Make column and find the average
car_sales.groupby(["Make"]).mean(numeric_only=True)

,Unnamed: 0.4,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,Odometer KM,Doors,Price
Make,,,,,,,,
BMW,3.000000,3.000000,3.000000,3.000000,3.000000,11179.000000,5.00,22000.0
Honda,4.666667,4.666667,4.666667,4.666667,4.666667,62778.333333,4.00,6500.0
Nissan,6.500000,6.500000,6.500000,6.500000,6.500000,122347.500000,4.00,6600.0
Toyota,3.750000,3.750000,3.750000,3.750000,3.750000,85451.250000,3.75,5437.5

In [25]:
# Import Matplotlib and create a plot of the Odometer column
# Don't forget to use %matplotlib inline
# %matplotlib inline
# import matplotlib.pyplot as plt
# car_sales["Odometer KM"].plot()

ModuleNotFoundError: No module named 'matplotlib'

In [26]:
# Create a histogram of the Odometer column using hist()
car_sales["Odometer KM"].hist()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [27]:
# Try to plot the Price column using plot()
car_sales["Price"].plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

Why didn't it work? Can you think of a solution?

You might want to search for "how to convert a pandas string column to numbers".

And if you're still stuck, check out this [Stack Overflow question and answer on turning a price column into integers](https://stackoverflow.com/questions/44469313/price-column-object-to-int-in-pandas).

See how you can provide the example code there to the problem here.

In [28]:
car_sales["Price"]

0     4000.0
1     5000.0
2     7000.0
3    22000.0
4     3500.0
5     4500.0
6     7500.0
7     7000.0
8     6250.0
9     9700.0
Name: Price, dtype: float64

In [32]:
# Remove the punctuation from price column
car_sales["Price"] = car_sales["Price"].replace(r"[\$\,\.]", "", regex=True)

In [33]:
# Check the changes to the price column
car_sales["Price"]

0     4000.0
1     5000.0
2     7000.0
3    22000.0
4     3500.0
5     4500.0
6     7500.0
7     7000.0
8     6250.0
9     9700.0
Name: Price, dtype: float64

In [ ]:
# Remove the two extra zeros at the end of the price column
car_sales["Price"] = car_sales["Price"].str[:-2]

In [34]:
# Check the changes to the Price column
car_sales["Price"]

0     4000.0
1     5000.0
2     7000.0
3    22000.0
4     3500.0
5     4500.0
6     7500.0
7     7000.0
8     6250.0
9     9700.0
Name: Price, dtype: float64

In [ ]:
# Change the datatype of the Price column to integers
car_sales["Price"] = car_sales["Price"].astype(int)

In [ ]:
# Lower the strings of the Make column
car_sales["Make"].str.lower()

If you check the car sales DataFrame, you'll notice the Make column hasn't been lowered.

How could you make these changes permanent?

Try it out.

In [ ]:
# Make lowering the case of the Make column permanent
car_sales["Make"] = car_sales["Make"].str.lower()

In [ ]:
# Check the car sales DataFrame
car_sales

Notice how the Make column stays lowered after reassigning.

Now let's deal with missing data.

In [ ]:
# Import the car sales DataFrame with missing data ("../data/car-sales-missing-data.csv")
car_sales_missing = pd.read_csv("../data/car-sales-missing-data.csv")

# Check out the new DataFrame
car_sales_missing

Notice the missing values are represented as `NaN` in pandas DataFrames.

Let's try fill them.

In [ ]:
# Fill the Odometer column missing values with the mean of the column inplace
car_sales_missing["Odometer"].fillna(car_sales_missing["Odometer"].mean(),
                                     inplace=True)

In [ ]:
# View the car sales missing DataFrame and verify the changes
car_sales_missing

In [ ]:
# Remove the rest of the missing data inplace
car_sales_missing.dropna(inplace=True)

In [ ]:
# Verify the missing values are removed by viewing the DataFrame
car_sales_missing

We'll now start to add columns to our DataFrame.

In [ ]:
# Create a "Seats" column where every row has a value of 5
car_sales["Seats"] = 5
car_sales

In [ ]:
# Create a column called "Engine Size" with random values between 1.3 and 4.5
# Remember: If you're doing it from a Python list, the list has to be the same length
# as the DataFrame
engine_sizes = [1.3, 4.3, 2.3, 3.3, 3.0, 2.3, 1.4, 1.7, 2.5, 3.1]
car_sales["Engine Size"] = engine_sizes
car_sales

In [ ]:
# Create a column which represents the price of a car per kilometer
# Then view the DataFrame
car_sales["Price per KM"] = car_sales["Price"] / car_sales["Odometer (KM)"]
car_sales

In [ ]:
# Remove the last column you added using .drop()
car_sales = car_sales.drop("Price per KM", axis=1)
car_sales

In [ ]:
# Shuffle the DataFrame using sample() with the frac parameter set to 1
# Save the the shuffled DataFrame to a new variable
car_sales_sampled = car_sales_sampled = car_sales.sample(frac=1)
car_sales_sampled

Notice how the index numbers get moved around. The [`sample()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.sample.html) function is a great way to get random samples from your DataFrame. It's also another great way to shuffle the rows by setting `frac=1`.

In [ ]:
# Reset the indexes of the shuffled DataFrame
car_sales_sampled.reset_index()

Notice the index numbers have been changed to have order (start from 0).

In [35]:
# Change the Odometer values from kilometers to miles using a Lambda function
# Then view the DataFrame
car_sales["Odometer (KM)"] = car_sales["Odometer (KM)"].apply(lambda x: x/1.6)
car_sales

IndentationError: expected an indented block after function definition on line 4 (559266367.py, line 5)

In [ ]:
# Change the title of the Odometer (KM) to represent miles instead of kilometers
car_sales = car_sales.rename(columns={"Odometer (KM)": "Odometer (Miles)"})
car_sales

## Extensions

For more exercises, check out the pandas documentation, particularly the [10-minutes to pandas section](https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html). 

One great exercise would be to retype out the entire section into a Jupyter Notebook of your own.

Get hands-on with the code and see what it does.

The next place you should check out are the [top questions and answers on Stack Overflow for pandas](https://stackoverflow.com/questions/tagged/pandas?sort=MostVotes&edited=true). Often, these contain some of the most useful and common pandas functions. Be sure to play around with the different filters!

Finally, always remember, the best way to learn something new to is try it. Make mistakes. Ask questions, get things wrong, take note of the things you do most often. And don't worry if you keep making the same mistake, pandas has many ways to do the same thing and is a big library. So it'll likely take a while before you get the hang of it.