In [8]:
import numpy as np
a = 10
b = 5
np.add(a,b)

np.int64(15)

In [10]:
import numpy as np
a = 86
b = 98
np.subtract(b,a)

np.int64(12)

In [13]:
import numpy as np
a = 7
b = 2
np.multiply(a,b)

np.int64(14)

In [14]:
import numpy as np
a2 = np.array([[1,2,3],[4,5,6]])
print(a2)

[[1, 2, 3], [4, 5, 6]]

In [21]:
import pandas as pd
df = pd.DataFrame(a2)
df

   0  1  2
0  1  2  3
1  4  5  6

In [26]:
import pandas as pd
ds = pd.Series([2,4,6,8,10])
print("sample output")
print(ds)

sample output
0     2
1     4
2     6
3     8
4    10
dtype: int64

In [32]:
import pandas as pd
a = pd.Series([2,4,6,8,10])
b = pd.Series([1,3,5,7,9])
ds= a + b
print("Add Two Series")
print(ds)
print("Subtract two Series")
ds = a - b 
print(ds)
print("multiply two series")
ds = a*b
print(ds)
print("divide two series")
ds = a/b
print(ds)

Add Two Series
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series
0    1
1    1
2    1
3    1
4    1
dtype: int64
multiply two series
0     2
1    12
2    30
3    56
4    90
dtype: int64
divide two series
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [33]:
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)

Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool

In [2]:
import pandas as pd
data = {"Name": ["Binish","Haris","Ellie","Dawood"],
        "Age": [12,22,31,28],
        "Grade": [85,92,78,95]}
df = pd.DataFrame(data)
df

     Name  Age  Grade
0  Binish   12     85
1   Haris   22     92
2   Ellie   31     78
3  Dawood   28     95

In [3]:
print(df["Name"])

0    Binish
1     Haris
2     Ellie
3    Dawood
Name: Name, dtype: str

In [4]:
print(df[df["Age"] > 20])

     Name  Age  Grade
1   Haris   22     92
2   Ellie   31     78
3  Dawood   28     95

In [6]:
df = df.sort_values(by = "Grade")
print(df)

     Name  Age  Grade
2   Ellie   31     78
0  Binish   12     85
1   Haris   22     92
3  Dawood   28     95

In [8]:
df = df.sort_values(by = "Names")
print(df)

TypeError: Series.sort_values() got an unexpected keyword argument 'by'

In [9]:
import pandas as pd
data = {"Name": ["Binish","Haris","Ellie","Dawood"],
        "Age": [12,22,31,28],
        "Grade": [85,92,78,95]}
df = pd.DataFrame(data)
df

     Name  Age  Grade
0  Binish   12     85
1   Haris   22     92
2   Ellie   31     78
3  Dawood   28     95

In [10]:
df = df.sort_values(by = "Name")
print(df)

     Name  Age  Grade
0  Binish   12     85
3  Dawood   28     95
2   Ellie   31     78
1   Haris   22     92

In [13]:
import pandas as pd
# Define the multipliers (1 to 10) and calculate results
data = {
    'Multiplier': range(1, 11),
    'Result': [i * 2 for i in range(1, 11)]
}

# Create the DataFrame
df = pd.DataFrame(data)

# Display the table
print(df)

   Multiplier  Result
0           1       2
1           2       4
2           3       6
3           4       8
4           5      10
5           6      12
6           7      14
7           8      16
8           9      18
9          10      20

In [17]:
import pandas as pd
data = {
    "Multiplier": range(1,11),
    "Result":[i* 3 for i in range(1,11)]}
df = pd.DataFrame(data)
print(df)

   Multiplier  Result
0           1       3
1           2       6
2           3       9
3           4      12
4           5      15
5           6      18
6           7      21
7           8      24
8           9      27
9          10      30

In [24]:
import pandas as pd
df = pd.read_excel("vlookup.xlsx")

In [23]:
print(df)

    Unnamed: 0  Unnamed: 1  Unnamed: 2  Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0          NaN         NaN         NaN         NaN        NaN        NaN
1          NaN         NaN         NaN         NaN        NaN        NaN
2          NaN         NaN         NaN         NaN       name    product
3          NaN         NaN         NaN         NaN       hari      apple
4          NaN         NaN         NaN         NaN        ali    samsung
5          NaN         NaN         NaN         NaN      rohit       vivo
6          NaN         NaN         NaN         NaN    radhika       oppo
7          NaN         NaN         NaN         NaN    anushka      nokia
8          NaN         NaN         NaN         NaN      aarti       lava
9          NaN         NaN         NaN         NaN   abhishek    samsung
10         NaN         NaN         NaN         NaN      samad      nokia
11         NaN         NaN         NaN         NaN       arsh         mi

   Unnamed: 6 Unnamed: 7
0         NaN        NaN
1         NaN        NaN
2      sales        cost
3          12      75000
4          15      14500
5          14      10000
6          52      16500
7          35      11500
8          14      12999
9          96      18999
10         54      14500
11         15      12000